# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Snippets of Thought'
tagline:          'insert tagline'
url:              https://cbarrick.github.io
paginate:         3
baseurl:          /
author:
  name:           'Chris Barrick'
  url:            https://cbarrick.github.io
  email:          cbarrick1@gmail.com
timezone:         US/Eastern
